#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.j722s libs
	$(MAKE) -f makefile.j722s libs-external
	$(MAKE) -f makefile.j722s sbl
	$(MAKE) -f makefile.j722s examples

clean: libs-clean libs-external-clean sbl-clean examples-clean
scrub: libs-scrub libs-external-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.j722s help
	@echo  .
	@echo  $(MAKE) -s -f makefile.j722s all
	@echo  $(MAKE) -s -f makefile.j722s clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.j722s scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.j722s libs
	@echo  $(MAKE) -s -f makefile.j722s libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.j722s libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.j722s examples
	@echo  $(MAKE) -s -f makefile.j722s examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.j722s examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets

# Combine all Components
BUILD_COMBO_ALL =

# Combine all External Components
BUILD_COMBO_EXTERNAL_ALL =

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-external: $(BUILD_COMBO_EXTERNAL_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)


# Various Component Clean Targets

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL =

# Combine all External Components Clean
BUILD_COMBO_EXTERNAL_CLEAN_ALL =

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-external-clean: $(BUILD_COMBO_EXTERNAL_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)


# Various Component Scrub Targets

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL =

# Combine all External Components Scrub Targets
BUILD_COMBO_EXTERNAL_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-external-scrub: $(BUILD_COMBO_EXTERNAL_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile all

 core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile all

 core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile clean

 core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 core_r5_test_j722s-evm_mcu-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/mcu-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 core_r5_test_j722s-evm_wkup-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/wkup-r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 core_r5_test_j722s-evm_main-r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl_core_r5_test/j722s-evm/main-r5fss0-0_nortos/ti-arm-clang -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:


host-emu:
	$(MAKE) -C source/drivers/dmautils -f makefile.j722s.c75ssx-0.ti-c7x-hostemu all

host-emu-clean:
	$(MAKE) -C source/drivers/dmautils -f makefile.j722s.c75ssx-0.ti-c7x-hostemu clean

host-emu-scrub:
	$(MAKE) -C source/drivers/dmautils -f makefile.j722s.c75ssx-0.ti-c7x-hostemu scrub

.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-external libs-external-clean libs-external-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
