#
# Auto generated makefile
#

all:
	$(MAKE) -f makefile.am275x libs
	$(MAKE) -f makefile.am275x libs-external
	$(MAKE) -f makefile.am275x sbl
	$(MAKE) -f makefile.am275x examples

clean: libs-clean libs-external-clean sbl-clean examples-clean
scrub: libs-scrub libs-external-scrub sbl-scrub examples-scrub

help:
	@echo  Notes,
	@echo  - Use -j to invoke parallel builds
	@echo  - Use PROFILE=debug or PROFILE=release [default] to build in debug or release profile
	@echo  .
	@echo  Overall build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am275x help
	@echo  .
	@echo  $(MAKE) -s -f makefile.am275x all
	@echo  $(MAKE) -s -f makefile.am275x clean  # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am275x scrub  # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am275x libs
	@echo  $(MAKE) -s -f makefile.am275x libs-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am275x libs-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  $(MAKE) -s -f makefile.am275x examples
	@echo  $(MAKE) -s -f makefile.am275x examples-clean # delete's tmp files for current profile
	@echo  $(MAKE) -s -f makefile.am275x examples-scrub # delete's all tmp files and folders for all profiles
	@echo  .
	@echo  Library build targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am275x unity_r5f.ti-arm-clang unity_c75x.ti-c7000
	@echo  .
	@echo  Library clean targets,
	@echo  ======================
	@echo  $(MAKE) -s -f makefile.am275x unity_r5f.ti-arm-clang_clean unity_c75x.ti-c7000_clean
	@echo  .
	@echo  Example build targets,
	@echo  ======================
	@echo  $(MAKE) -s -C drivers/sciclient/sciclient_get_version/am275x-evm/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/sciclient/sciclient_get_version/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C drivers/uart/am275x-evm/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am275x-evm/r5fss0-0_nortos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am275x-evm/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am275x-evm/c75ss0-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/dpl/am275x-evm/c75ss1-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am275x-evm/r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang [all clean syscfg-gui syscfg]
	@echo  $(MAKE) -s -C kernel/freertos/am275x-evm/c75ss0-0_freertos/ti-c7000 [all clean syscfg-gui syscfg]
	@echo  .
	@echo  System Example build targets,
	@echo  =============================
	@echo  .

# Various Component Targets
BUILD_COMBO_unity = unity_r5f.ti-arm-clang unity_c75x.ti-c7000

# Combine all Components
BUILD_COMBO_ALL = $(BUILD_COMBO_unity)

# Combine all External Components
BUILD_COMBO_EXTERNAL_ALL =

# Combine all Pre-built Components
BUILD_COMBO_PREBUILT_ALL =

# Combine all Private Components
BUILD_COMBO_PRIVATE_ALL =

libs: $(BUILD_COMBO_ALL)

libs-external: $(BUILD_COMBO_EXTERNAL_ALL)

libs-prebuilt: $(BUILD_COMBO_PREBUILT_ALL)

libs-private: $(BUILD_COMBO_PRIVATE_ALL)

$(BUILD_COMBO_unity):
	$(MAKE) -C unity -f makefile.am275x.$(subst unity_,,$@) all


# Various Component Clean Targets
BUILD_COMBO_CLEAN_unity = unity_r5f.ti-arm-clang_clean unity_c75x.ti-c7000_clean

# Combine all Components Clean
BUILD_COMBO_CLEAN_ALL = $(BUILD_COMBO_CLEAN_unity)

# Combine all External Components Clean
BUILD_COMBO_EXTERNAL_CLEAN_ALL =

# Combine all Pre-built Components Clean
BUILD_COMBO_PREBUILT_CLEAN_ALL =

libs-clean: $(BUILD_COMBO_CLEAN_ALL)

libs-external-clean: $(BUILD_COMBO_EXTERNAL_CLEAN_ALL)

libs-prebuilt-clean: $(BUILD_COMBO_PREBUILT_CLEAN_ALL)

$(BUILD_COMBO_CLEAN_unity):
	$(MAKE) -C unity -f makefile.am275x.$(subst unity_,,$(subst _clean,,$@)) clean


# Various Component Scrub Targets
BUILD_COMBO_SCRUB_unity = unity_r5f.ti-arm-clang_scrub unity_c75x.ti-c7000_scrub_scrub

# Combine all Components Scrub Targets
BUILD_COMBO_SCRUB_ALL = $(BUILD_COMBO_SCRUB_unity)

# Combine all External Components Scrub Targets
BUILD_COMBO_EXTERNAL_SCRUB_ALL =

# Combine all Pre-built Components Scrub Targets
BUILD_COMBO_PREBUILT_SCRUB_ALL =

libs-scrub: $(BUILD_COMBO_SCRUB_ALL)

libs-external-scrub: $(BUILD_COMBO_EXTERNAL_SCRUB_ALL)

libs-prebuilt-scrub: $(BUILD_COMBO_PREBUILT_SCRUB_ALL)

$(BUILD_COMBO_SCRUB_unity):
	$(MAKE) -C unity -f makefile.am275x.$(subst unity_,,$(subst _scrub,,$@)) scrub


BUILD_COMBO_EXAMPLE_ALL =
# Various Example Targets
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_am275x-evm_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_sciclient_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_uart_am275x-evm_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am275x-evm_r5fss0-0_nortos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am275x-evm_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am275x-evm_c75ss0-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_dpl_am275x-evm_c75ss1-0_freertos_ti-c7000
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am275x-evm_r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang
BUILD_COMBO_EXAMPLE_ALL += test_freertos_am275x-evm_c75ss0-0_freertos_ti-c7000
# Various System Example Targets

BUILD_COMBO_EXAMPLE_PRIVATE_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples: $(BUILD_COMBO_EXAMPLE_ALL)

examples-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL)

 test_sciclient_am275x-evm_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/am275x-evm/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_sciclient_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_uart_am275x-evm_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C drivers/uart/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am275x-evm_r5fss0-0_nortos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am275x-evm/r5fss0-0_nortos/ti-arm-clang -f makefile all

 test_dpl_am275x-evm_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/dpl/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_dpl_am275x-evm_c75ss0-0_freertos_ti-c7000:
	$(MAKE) -C kernel/dpl/am275x-evm/c75ss0-0_freertos/ti-c7000 -f makefile all

 test_dpl_am275x-evm_c75ss1-0_freertos_ti-c7000:
	$(MAKE) -C kernel/dpl/am275x-evm/c75ss1-0_freertos/ti-c7000 -f makefile all

 test_freertos_am275x-evm_r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang:
	$(MAKE) -C kernel/freertos/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile all

 test_freertos_am275x-evm_c75ss0-0_freertos_ti-c7000:
	$(MAKE) -C kernel/freertos/am275x-evm/c75ss0-0_freertos/ti-c7000 -f makefile all


BUILD_COMBO_EXAMPLE_CLEAN_ALL =
# Various Example Clean Targets
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_am275x-evm_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_sciclient_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_uart_am275x-evm_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am275x-evm_r5fss0-0_nortos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am275x-evm_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am275x-evm_c75ss0-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_dpl_am275x-evm_c75ss1-0_freertos_ti-c7000_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am275x-evm_r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean
BUILD_COMBO_EXAMPLE_CLEAN_ALL += test_freertos_am275x-evm_c75ss0-0_freertos_ti-c7000_clean
# Various System Example Clean Targets

BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-clean: $(BUILD_COMBO_EXAMPLE_CLEAN_ALL)

examples-private-clean: $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL)

 test_sciclient_am275x-evm_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/am275x-evm/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_sciclient_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_uart_am275x-evm_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C drivers/uart/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am275x-evm_r5fss0-0_nortos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am275x-evm/r5fss0-0_nortos/ti-arm-clang -f makefile clean

 test_dpl_am275x-evm_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/dpl/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_dpl_am275x-evm_c75ss0-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/dpl/am275x-evm/c75ss0-0_freertos/ti-c7000 -f makefile clean

 test_dpl_am275x-evm_c75ss1-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/dpl/am275x-evm/c75ss1-0_freertos/ti-c7000 -f makefile clean

 test_freertos_am275x-evm_r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_clean:
	$(MAKE) -C kernel/freertos/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile clean

 test_freertos_am275x-evm_c75ss0-0_freertos_ti-c7000_clean:
	$(MAKE) -C kernel/freertos/am275x-evm/c75ss0-0_freertos/ti-c7000 -f makefile clean


BUILD_COMBO_EXAMPLE_SCRUB_ALL =
# Various Example Scrub Targets
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_am275x-evm_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_sciclient_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_uart_am275x-evm_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am275x-evm_r5fss0-0_nortos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am275x-evm_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am275x-evm_c75ss0-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_dpl_am275x-evm_c75ss1-0_freertos_ti-c7000_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am275x-evm_r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub
BUILD_COMBO_EXAMPLE_SCRUB_ALL += test_freertos_am275x-evm_c75ss0-0_freertos_ti-c7000_scrub
# Various System Example Scrub Targets

BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL =
# Various Private Example Targets
# Various Private System Example Targets

examples-scrub: $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)

examples-scrub-private: $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)

 test_sciclient_am275x-evm_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/am275x-evm/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_sciclient_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/sciclient/sciclient_get_version/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_uart_am275x-evm_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C drivers/uart/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am275x-evm_r5fss0-0_nortos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am275x-evm/r5fss0-0_nortos/ti-arm-clang -f makefile scrub

 test_dpl_am275x-evm_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/dpl/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_dpl_am275x-evm_c75ss0-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/dpl/am275x-evm/c75ss0-0_freertos/ti-c7000 -f makefile scrub

 test_dpl_am275x-evm_c75ss1-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/dpl/am275x-evm/c75ss1-0_freertos/ti-c7000 -f makefile scrub

 test_freertos_am275x-evm_r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am275x-evm/r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am275x-evm_wkup-r5fss0-0_freertos_ti-arm-clang_scrub:
	$(MAKE) -C kernel/freertos/am275x-evm/wkup-r5fss0-0_freertos/ti-arm-clang -f makefile scrub

 test_freertos_am275x-evm_c75ss0-0_freertos_ti-c7000_scrub:
	$(MAKE) -C kernel/freertos/am275x-evm/c75ss0-0_freertos/ti-c7000 -f makefile scrub


sbl: libs

sbl-clean:

sbl-scrub:



.PHONY: all clean scrub help
.PHONY: libs libs-clean libs-scrub
.PHONY: libs-external libs-external-clean libs-external-scrub
.PHONY: libs-private
.PHONY: libs-prebuilt libs-prebuilt-clean libs-prebuilt-scrub
.PHONY: examples examples-clean examples-scrub
.PHONY: examples-private examples-private-clean examples-private-scrub
.PHONY: sbl sbl-clean sbl-scrub
.PHONY: $(BUILD_COMBO_ALL) $(BUILD_COMBO_CLEAN_ALL) $(BUILD_COMBO_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_ALL) $(BUILD_COMBO_EXAMPLE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_SCRUB_ALL)
.PHONY: $(BUILD_COMBO_EXAMPLE_PRIVATE_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_CLEAN_ALL) $(BUILD_COMBO_EXAMPLE_PRIVATE_SCRUB_ALL)
